export const ADD = "SPRINTS/ADD";
export const LOAD_DATA = "SPRINTS/LOAD_DATA";
export const DELETE = "SPRINTS/DELETE";
export const EDIT = "SPRINTS/EDIT";
export const COMPLETE = "SPRINTS/COMPLETE";
export const COMPLETE_ALL = "SPRINTS/COMPLETE_ALL";
export const CLEAR_COMPLETED = "SPRINTS/CLEAR_COMPLETED";
