export const initialState = {
  byId: {
    abc123: {
      id: "abc123",
      model: "releases",
      label: "Release 157",
      quarterId: {model: "quarters", id: "abc123"},
      status: "resolved",
    },
    def234: {
      id: "def234",
      model: "releases",
      label: "Release 158",
      quarterId: {model: "quarters", id: "abc123"},
      status: "active",
    },
    fds343: {
      id: "fds343",
      model: "releases",
      label: "Release 159",
      quarterId: {model: "quarters", id: "abc123"},
      status: "planned",
    },
    xcy343: {
      id: "xcy343",
      model: "releases",
      label: "Release 160",
      quarterId: {model: "quarters", id: "abc123"},
      status: "planned",
    },
    qqqqqq: {
      id: "qqqqqq",
      model: "releases",
      label: "Release 161",
      quarterId: {model: "quarters", id: "def234"},
      status: "resolved",
    },
    wwwwww: {
      id: "wwwwww",
      model: "releases",
      label: "Release 162",
      quarterId: {model: "quarters", id: "def234"},
      status: "resolved",
    },
    rrrrrr: {
      id: "rrrrrr",
      model: "releases",
      label: "Release 163",
      quarterId: {model: "quarters", id: "def234"},
      status: "active",
    },
    tttttt: {
      id: "tttttt",
      model: "releases",
      label: "Release 164",
      quarterId: {model: "quarters", id: "def234"},
      status: "planned",
    },
  },
};
