export const initialState = {
  byId: {
    abc123: {
      id: "abc123",
      model: "quarters",
      label: "2021-Q3",
      projectId: {model: "projects", id: "abc123"},
      status: "RESOLVED",
    },
    def234: {
      id: "def234",
      model: "quarters",
      label: "2021-Q4",
      projectId: {model: "projects", id: "abc123"},
      status: "ACTIVE",
    },
    fds343: {
      id: "fds343",
      model: "quarters",
      label: "2022-Q1",
      projectId: {model: "projects", id: "abc123"},
      status: "PLANNED",
    },
    xcy343: {
      id: "xcy343",
      model: "quarters",
      label: "2022-Q2",
      projectId: {model: "projects", id: "abc123"},
      status: "PLANNED",
    },
    fdsfds: {
      id: "fdsfds",
      model: "quarters",
      label: "2022-Q3",
      projectId: {model: "projects", id: "def234"},
      status: "RESOLVED",
    },
    hghghg: {
      id: "hghghg",
      model: "quarters",
      label: "2022-Q4",
      projectId: {model: "projects", id: "def234"},
      status: "RESOLVED",
    },
    ututuy: {
      id: "ututuy",
      model: "quarters",
      label: "2023-Q1",
      projectId: {model: "projects", id: "def234"},
      status: "ACTIVE",
    },
    ppooii: {
      id: "ppooii",
      model: "quarters",
      label: "2023-Q2",
      projectId: {model: "projects", id: "def234"},
      status: "PLANNED",
    },
  },
};
