export const CREATE = "TICKETS/CREATE";
export const LOAD_DATA = "TICKETS/LOAD_DATA";
export const DELETE = "TICKETS/DELETE";
export const EDIT = "TICKETS/EDIT";
export const COMPLETE = "TICKETS/COMPLETE";
export const COMPLETE_ALL = "TICKETS/COMPLETE_ALL";
export const CLEAR_COMPLETED = "TICKETS/CLEAR_COMPLETED";
