export const initialState = {
  byId: {
    abc123: {
      id: "abc123",
      model: "days",
      label: "MON",
      parentId: {model: "sprints", id: "abc123"},
      status: "RESOLVED",
    },
    def234: {
      id: "def234",
      model: "days",
      label: "TUE",
      parentId: {model: "sprints", id: "abc123"},
      status: "ACTIVE",
    },
    fds343: {
      id: "fds343",
      model: "days",
      label: "WED",
      parentId: {model: "sprints", id: "abc123"},
      status: "PLANNED",
    },
    xcy343: {
      id: "xcy343",
      model: "days",
      label: "THOR",
      parentId: {model: "sprints", id: "abc123"},
      status: "PLANNED",
    },
    uuuuuu: {
      id: "uuuuuu",
      model: "days",
      label: "MON",
      parentId: {model: "sprints", id: "def234"},
      status: "RESOLVED",
    },
    iiiiii: {
      id: "iiiiii",
      model: "days",
      label: "TUE",
      parentId: {model: "sprints", id: "def234"},
      status: "ACTIVE",
    },
    oooooo: {
      id: "oooooo",
      model: "days",
      label: "WED",
      parentId: {model: "sprints", id: "def234"},
      status: "PLANNED",
    },
    pppppp: {
      id: "pppppp",
      model: "days",
      label: "THOR",
      parentId: {model: "sprints", id: "def234"},
      status: "PLANNED",
    },
  },
};
