export const ADD = "PROJECTS/ADD";
export const FETCH = "PROJECTS/FETCH";
export const LOAD_DATA = "PROJECTS/LOAD_DATA";
export const DELETE = "PROJECTS/DELETE";
export const EDIT = "PROJECTS/EDIT";
export const COMPLETE = "PROJECTS/COMPLETE";
export const COMPLETE_ALL = "PROJECTS/COMPLETE_ALL";
export const CLEAR_COMPLETED = "PROJECTS/CLEAR_COMPLETED";
